# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efe22bcdcbb61a1f54e34c3679f4c8a1b441755c61c106de12f748dfdf395f66c56dac807378b6716529e08d4e6c669ff4e1548f5c59c21dbf8c30b34749b9a8

test:
  secret_key_base: a898972acb1611e14f098d553f04125db0b15369f80ca157f90789c8433e1f0c8df56bd332bd3895637a7910a78b130abf639a306f5572428c1e7ce3eb94da5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
